authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp_views

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp_views.login, name='login'),
    path('logout/', authapp_views.logout, name='logout'),
    path('register/', authapp_views.register, name='register'),
    path('edit/', authapp_views.edit, name='edit'),
    path('verify/<email>/<activate_key>/', authapp_views.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remall/', basketapp.basket_all_remove, name='remove_all'),
    path('remove/<int:id>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:id>/<int:quantity>/', basketapp.basket_edit, name='basket_edit')
]

geekshop/urls.py
"""geekshop URL Configuration"""

from django.urls import path, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp_views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.main, name='index'),
    path('contact/', mainapp_views.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path, path

app_name = "ordersapp"

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('price/<int:pk>/', ordersapp.get_item_price, name='get_item_price'),
    path('read/<pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product
from django.utils.functional import cached_property

# class BasketQuerySet(models.QuerySet):
#
#     def delete(self, *args, **kwargs):
#         for object in self:
#             object.product.quantity += object.quantity
#             object.product.save()
#         super(BasketQuerySet, self).delete(*args, **kwargs)


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='время', auto_now_add=True)

    # objects = BasketQuerySet.as_manager()

    def __str__(self):
        """
        Переопределение стандартного метода str
        :return: Возвращает заданное пользователем представление экземпляра класса
        """
        return f'{self.user} - {self.product}'

    # @cached_property
    # def get_items_cached(self):
    #     return self.user.basket.select_related()
    #
    # def get_total_quantity(self):
    #     _items = self.get_items_cached
    #     return sum(list(map(lambda x: x.quantity, _items)))
    #
    # def get_total_cost(self):
    #     _items = self.get_items_cached
    #     return sum(list(map(lambda x: x.product_cost, _items)))
    #

    def sum(self):
        return self.quantity * self.product.price

    # Решение сигналами
    @staticmethod
    def getitem(pk):
        return Basket.objects.filter(pk=pk).first()

    @staticmethod
    def get_items(user, product=None):
        if product:
            return Basket.objects.filter(user=user, product=product).select_related()
        return Basket.objects.filter(user=user).select_related()

    # Решение изменением моделей
    # def delete(self):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super(self.__class__, self).delete()
    #
    # def save(self, *args, **kwargs):
    #     if self.pk:
    #         self.product.quantity -= self.quantity - self.__class__.get_item(self.pk).quantity
    #     else:
    #         self.product.quantity -= self.quantity
    #     self.product.save()
    #     super(self.__class__, self).save(*args, **kwargs)

basketapp/views.py
from django.db.models import F
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product
from django.template.loader import render_to_string
from django.http import JsonResponse
from authapp.forms import ShopUserEditForm
from django.contrib.auth.decorators import login_required


def get_product(user, product=None):
    return Basket.objects.filter(user=user, product=product)


@login_required
def basket(request):
    title = 'Просмотр корзины'
    edit_form = ShopUserEditForm(instance=request.user)
    baskets = Basket.get_items(user=request.user)
    content = {
        'title': title,
        'edit_form': edit_form,
        'baskets': baskets,
        'total_quantity': sum(basket.quantity for basket in baskets),
        'total_sum': sum(basket.sum() for basket in baskets),
    }
    return render(request, 'authapp/profile.html', content)


@login_required
def basket_add(request, pk):
    product = get_object_or_404(Product, pk=pk)
    basket = Basket.get_items(user=request.user, product=product).first()
    if not basket:
        basket = Basket(user=request.user, product=product)
    basket.quantity += 1
    basket.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_all_remove(request):
    baskets = Basket.get_items(user=request.user)
    for basket in baskets:
        basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, id):
    basket = Basket.objects.get(id=id)
    basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, id, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        basket = Basket.objects.get(id=int(id))
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()
        baskets = Basket.get_items(user=request.user)
        context = {
            'baskets': baskets,
            'total_quantity': sum(basket.quantity for basket in baskets),
            'total_sum': sum(basket.sum() for basket in baskets),
        }
        result = render_to_string('basketapp/basket.html', context)
        return JsonResponse({'result': result})

basketapp/templates/basketapp/basket.html
<div class="basket_list">
    {% if baskets %}
        <div class="card-header">
            <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
            </h4>
            <a href="{% url 'basketapp:remove_all' %}">
                <i class="fas fa-trash"></i>
            </a>
        </div>
        {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.short_desc }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row">
                            <div class="col-lg-4">
                                <input name="{{ basket.id }}" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">
                                {{ basket.sum }} руб.
                            </div>
                            <div class="col-lg-4">
                                <a href="{% url 'basketapp:remove' basket.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="card-text float-left">Итого:</p>
                <h5 class="card-text float-right">{{ total_sum }} руб.</h5>
            </div>
            <div class="card">
                <a href="{% url 'ordersapp:order_create' %}" class="float-left btn btn-lg btn-success">
                    Оформить заказ
                </a>
                <a href="{% url 'basketapp:remove_all' %}" class="float-right btn btn-warning btn-lg">
                    Очистить корзину
                </a>
            </div>
        </div>

    {% else %}
        <h4 class="mt-3 mb-3 mb-3 text-center">Корзина пуста</h4>
    {% endif %}
</div>