adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp_views

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp_views.index, name='index'),
    path('users/', adminapp_views.AdminUsers.as_view(), name='admin_users'),
    # path('users/', adminapp_views.admin_users, name='admin_users'),
    path('users/create/', adminapp_views.AdminUsersCreate.as_view(), name='admin_users_create'),
    # path('users/create/', adminapp_views.admin_users_create, name='admin_users_create'),
    path('users/update/<int:pk>/', adminapp_views.AdminUsersUpdate.as_view(), name='admin_users_update'),
    # path('users/update/<int:user_id>/', adminapp_views.admin_users_update, name='admin_users_update'),
    path('users/remove/<int:pk>/', adminapp_views.AdminUsersRemove.as_view(), name='admin_users_remove'),
    # path('users/remove/<int:user_id>/', adminapp_views.admin_users_remove, name='admin_users_remove'),
    path('users/active/<int:pk>/', adminapp_views.AdminUsersActive.as_view(), name='admin_users_active'),
    # path('users/active/<int:user_id>/', adminapp_views.admin_users_active, name='admin_users_active'),

    path('categories/', adminapp_views.categories_item, name='categories'),
    path('categories/create/', adminapp_views.categories_item_create, name='categories_item_create'),
    path('categories/update/<int:category_pk>/', adminapp_views.ProductCategoryUpdateView.as_view(), name='categories_item_update'),
    #path('categories/update/<int:category_pk>/', adminapp_views.categories_item_update, name='categories_item_update'),
    path('categories/remove/<int:category_pk>/', adminapp_views.categories_item_remove, name='categories_item_remove'),
    path('categories/active/<int:category_pk>/', adminapp_views.categories_item_active, name='categories_item_active'),

    path('products/', adminapp_views.products_item, name='products'),
    path('products/create/', adminapp_views.products_item_create, name='products_item_create'),
    path('products/update/<int:product_pk>/', adminapp_views.products_item_update, name='products_item_update'),
    path('products/remove/<int:product_pk>/', adminapp_views.products_item_remove, name='products_item_remove'),
    path('products/active/<int:product_pk>/', adminapp_views.products_item_active, name='products_item_active'),
]

authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp_views

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp_views.login, name='login'),
    path('logout/', authapp_views.logout, name='logout'),
    path('register/', authapp_views.register, name='register'),
    path('edit/', authapp_views.edit, name='edit'),
    path('verify/<email>/<activate_key>/', authapp_views.verify, name='verify'),
]

geekshop/urls.py
"""geekshop URL Configuration"""

from django.urls import path, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp_views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.main, name='index'),
    path('contact/', mainapp_views.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp_views

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp_views.products, name='index'),
    path('category/<int:pk>/', mainapp_views.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', cache_page(3600)(mainapp_views.products), name='page'),
    path('product/<int:pk>/', mainapp_views.product_item, name='product'),

]

adminapp/forms.py
from authapp.forms import ShopUserRegisterForm, ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory
from django import forms


class UserAdminRegisterForm(ShopUserRegisterForm):
    avatar = forms.ImageField(widget=forms.FileInput)

    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'avatar')

    def __init__(self, *args, **kwargs):
        super(UserAdminRegisterForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'


class UserAdminEditForm(ShopUserEditForm):
    avatar = forms.ImageField(widget=forms.FileInput)

    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'birthday', 'avatar')
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super(UserAdminEditForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = False
        self.fields['email'].widget.attrs['readonly'] = False
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        #fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.exclude.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductsEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductsEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.db import connection
from django.db.models import F
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from authapp.models import ShopUser
from adminapp.forms import UserAdminRegisterForm, UserAdminEditForm, ProductCategoryEditForm, ProductsEditForm
from django.urls import reverse, reverse_lazy
from utilities.files import calculate_age, change_state
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from mainapp.models import Product, ProductCategory
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.
def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)


@user_passes_test(lambda u: u.is_superuser)
def index(request):
    user = ShopUser.objects.all()
    category = ProductCategory.objects.all()
    product = Product.objects.all()
    context = {
        'user': user,
        'category': category,
        'product': product,
    }
    return render(request, 'adminapp/index.html', context)


# CBV
class AdminUsers(ListView):
    model = ShopUser
    template_name = 'adminapp/admin-users-read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminUsers, self).dispatch(request, *args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def admin_users(request):
#     context = {
#         'users': ShopUser.objects.all(),
#     }
#     return render(request, 'adminapp/admin-users-read.html', context)


# CBV
class AdminUsersCreate(CreateView):
    model = ShopUser
    template_name = 'adminapp/admin-users-create.html'
    success_url = reverse_lazy('admin_staff:admin_users')
    form_class = UserAdminRegisterForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminUsersCreate, self).dispatch(request, *args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def admin_users_create(request):
#     if request.method == 'POST':
#         form = UserAdminRegisterForm(data=request.POST, files=request.FILES)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Пользователь успешно создан!')
#             return HttpResponseRedirect(reverse('admin_staff:admin_users'))
#         else:
#             messages.warning(request, form.errors)
#     else:
#         form = UserAdminRegisterForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'adminapp/admin-users-create.html', context)


# CBV
class AdminUsersUpdate(UpdateView):
    model = ShopUser
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('admin_staff:admin_users')
    form_class = UserAdminEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminUsersUpdate, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AdminUsersUpdate, self).get_context_data(**kwargs)
        context['title'] = title = 'редактирование'
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def admin_users_update(request, user_id):
#     user = get_object_or_404(ShopUser, id=user_id)
#     title = 'редактирование'
#     if request.method == 'POST':
#         # Подсчитываем возраст автоматически на основании даты рождения
#         try:
#             _mutable = request.POST._mutable
#             request.POST._mutable = True
#             request.POST['age'] = calculate_age(request.POST['birthday'])
#             request.POST._mutable = _mutable
#         except:
#             messages.warning(request, 'Не указана дата рождения! Возраст не определен, и оставлен без изменения!')
#
#         edit_form = UserAdminEditForm(request.POST, request.FILES, instance=user)
#         if edit_form.is_valid():
#             edit_form.save()
#             messages.success(request, 'Изменения успешно сохранены!')
#             return HttpResponseRedirect(reverse('admin_staff:admin_users'))
#         else:
#             messages.warning(request, 'Вы слишком молоды!')
#     else:
#         edit_form = UserAdminEditForm(instance=user)
#     context = {
#         'title': title,
#         'form': edit_form,
#         'user': user,
#     }
#     return render(request, 'adminapp/admin-users-update-delete.html', context)


# CBV
class AdminUsersRemove(DeleteView):
    model = ShopUser
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('admin_staff:admin_users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# @user_passes_test(lambda u: u.is_superuser)
# def admin_users_remove(request, user_id):
#     change_state(request, ShopUser, user_id, False, 'Пользователь успешно деактивирован!')
#     return HttpResponseRedirect(reverse('admin_staff:admin_users'))

# CBV
class AdminUsersActive(DeleteView):
    model = ShopUser
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('admin_staff:admin_users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# @user_passes_test(lambda u: u.is_superuser)
# def admin_users_active(request, user_id):
#     change_state(request, ShopUser, user_id, True, 'Пользователь успешно активирован!')
#     return HttpResponseRedirect(reverse('admin_staff:admin_users'))


@user_passes_test(lambda u: u.is_superuser)
def categories_item(request):
    context = {
        'categories': ProductCategory.objects.all().select_related()
    }
    return render(request, 'adminapp/categories-items-read.html', context)


@user_passes_test(lambda u: u.is_superuser)
def categories_item_create(request):
    if request.method == 'POST':
        form = ProductCategoryEditForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Категория успешно создана!')
            return HttpResponseRedirect(reverse('admin_staff:categories'))
        else:
            messages.warning(request, form.errors)
    else:
        form = ProductCategoryEditForm()
    context = {
        'form': form,
    }
    return render(request, 'adminapp/categories-item-create.html', context)


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/categories-item-update.html'
    success_url = reverse_lazy('admin:categories')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(ProductCategoryUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)

        return super().form_valid(form)


# @user_passes_test(lambda u: u.is_superuser)
# def categories_item_update(request, category_pk):
#     category = get_object_or_404(ProductCategory, pk=category_pk)
#     if request.method == 'POST':
#         form = ProductCategoryEditForm(data=request.POST, instance=category)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Категория успешно изменена!')
#             return HttpResponseRedirect(reverse('admin_staff:categories'))
#         else:
#             messages.warning(request, form.errors)
#     else:
#         form = ProductCategoryEditForm(instance=category)
#     context = {
#         'form': form,
#         'category': category,
#     }
#     return render(request, 'adminapp/categories-item-update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def categories_item_remove(request, category_pk):
    change_state(request, ProductCategory, category_pk, False, 'Категория успешно деактивированна!')
    return HttpResponseRedirect(reverse('admin_staff:categories'))


@user_passes_test(lambda u: u.is_superuser)
def categories_item_active(request, category_pk):
    change_state(request, ProductCategory, category_pk, True, 'Категория успешно активированна!')
    return HttpResponseRedirect(reverse('admin_staff:categories'))


@user_passes_test(lambda u: u.is_superuser)
def products_item(request):
    context = {
        'products': Product.objects.all().select_related()
    }
    return render(request, 'adminapp/products-items-read.html', context)


@user_passes_test(lambda u: u.is_superuser)
def products_item_create(request):
    if request.method == 'POST':

adminapp/templates/adminapp/admin-users-read.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <h1 class="mt-4">Пользователи</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Пользователи
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Имя пользователя</th>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Адрес эл. почты</th>
                        <th>Персонал сайта</th>
                        <th>Активный</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Имя пользователя</th>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Адрес эл. почты</th>
                        <th>Персонал сайта</th>
                        <th>Активный</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for elem in object_list %}
                        <tr {% if not elem.is_active %} class="text-muted" {% endif %}>
                            <td><a href="{% url 'admin_staff:admin_users_update' elem.id %}"
                                   style="color: dodgerblue">{{ elem.username }}</a></td>
                            <td>{{ elem.first_name }}</td>
                            <td>{{ elem.last_name }}</td>
                            <td>{{ elem.email }}</td>
                            <td class="text-center">
                                {% if elem.is_superuser or elem.is_staff %}
                                    <i class="fas fa-check-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if elem.is_active %}
                                    <i class="fas fa-check-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'admin_staff:admin_users_create' %}">
                <button class="btn btn-success">Создать пользователя</button>
            </a>
        </div>
    </div>
    {% if messages %}
        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

adminapp/templates/adminapp/admin-users-update-delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
    <div class="card-body">
        <form action="{% url 'admin_staff:admin_users_update' user.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                        {{ form.last_name }}
                    </div>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="col-lg-12">
                    <div class="custom-file">
                        {{ form.avatar }}
                        <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите
                            изображение</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                        почты</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.birthday.id_for_label }}">День рождения</label>
                    {{ form.birthday }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                    {{ form.age }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
        <div class="row">
            {% if shopuser.is_active %}
                <div class="col-lg-12" style="margin-top: 33px;">
                    <form action="{% url 'admin_staff:admin_users_remove' shopuser.pk %}" method="post">
                        {% csrf_token %}
                        {#                    <a href="{% url 'admin_staff:admin_users_remove' user.id %}">#}
                        <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        {#                    </a>#}
                    </form>
                </div>
            {% else %}
                <div class="col-lg-12" style="margin-top: 33px;">
                    <form action="{% url 'admin_staff:admin_users_active' shopuser.pk %}" method="post">
                        {% csrf_token %}
                        {#                    <a href="{% url 'admin_staff:admin_users_active' user.id %}">#}
                        <input class="btn btn-success btn-block" type="submit" value="Восстановить">
                        {#                    </a>#}
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/base.html
{% load static %}
{% load custom %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - {{ title|title }}</title>
    <link href="{% static '/css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="{% url 'mainapp:index' %}"><i
            class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'auth:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'adminapp:admin_users' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'admin_staff:categories' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="{% url 'admin_staff:products' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop {% now 'Y' %}</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js' %}"></script>
</body>
</html>

adminapp/templates/adminapp/categories-item-create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <h1 class="mt-4">Создание категории</h1>
    <form action="{% url 'admin_staff:categories_item_create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
    </form>
{% endblock %}

adminapp/templates/adminapp/categories-item-update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <h1 class="mt-4">Изменение категории</h1>
    <form action="{% url 'admin_staff:categories_item_update' 1 %}" method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
    </form>
    <div class="row">
        {% if category.is_active %}
            <div class="col-lg-12" style="margin-top: 33px;">
                <a href="{% url 'admin_staff:categories_item_remove' category.pk %}">
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </a>
            </div>
        {% else %}
            <div class="col-lg-12" style="margin-top: 33px;">
                <a href="{% url 'admin_staff:categories_item_active' category.pk %}">
                    <input class="btn btn-success btn-block" type="submit" value="Восстановить">
                </a>
            </div>
        {% endif %}
    </div>
{% endblock %}

adminapp/templates/adminapp/products-item-update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <h1 class="mt-4">Изменение продукта</h1>
    <form action="{% url 'admin_staff:products_item_update' product.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
    </form>
    <div class="row">
        {% if product.is_active %}
            <div class="col-lg-12" style="margin-top: 33px;">
                <a href="{% url 'admin_staff:products_item_remove' product.pk %}">
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </a>
            </div>
        {% else %}
            <div class="col-lg-12" style="margin-top: 33px;">
                <a href="{% url 'admin_staff:products_item_active' product.pk %}">
                    <input class="btn btn-success btn-block" type="submit" value="Восстановить">
                </a>
            </div>
        {% endif %}
    </div>
{% endblock %}