authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp_views

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp_views.login, name='login'),
    path('logout/', authapp_views.logout, name='logout'),
    path('register/', authapp_views.register, name='register'),
    path('edit/', authapp_views.edit, name='edit'),
    path('verify/<email>/<activate_key>/', authapp_views.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remall/', basketapp.basket_all_remove, name='remove_all'),
    path('remove/<int:id>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:id>/<int:quantity>/', basketapp.basket_edit, name='basket_edit')
]

geekshop/urls.py
"""geekshop URL Configuration"""

from django.urls import path, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp_views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.main, name='index'),
    path('contact/', mainapp_views.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp_views

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp_views.products, name='index'),
    path('category/<int:pk>/', mainapp_views.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', cache_page(3600)(mainapp_views.products), name='page'),
    path('product/<int:pk>/', mainapp_views.product_item, name='product'),

]

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path, path

app_name = "ordersapp"

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('price/<int:pk>/', ordersapp.get_item_price, name='get_item_price'),
    path('read/<pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

mainapp/models.py
from django.db import models
from utilities.files import get_file_path


class ProductCategory(models.Model):
    """
    Модель категориий продуктов
    """
    uid = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    def __str__(self):
        """
        Переопределение стандартного метода str
        :return: Возвращает заданное пользователем представление экземпляра класса
        """
        return self.name


class Product(models.Model):
    """
    Модель продукта.
    """
    uid = models.AutoField(primary_key=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to=get_file_path, blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    def __str__(self):
        """
        Переопределение стандартного метода str
        :return: Возвращает заданное пользователем представление экземпляра класса
        """
        return f'{self.name}'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
import random
from django.views.decorators.cache import cache_page
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.core.cache import cache

def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                'price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def get_hot_product():
    products = get_products()
    return random.sample(list(products), 1)[0]


def main(request):
    context = {
        'title': 'GeekShop',
    }
    return render(request, 'mainapp/index.html', context)


def product_item(request, pk=None):
    title = 'GeekShop - Каталог'
    # categories = ProductCategory.objects.all()
    categories = get_links_menu()
    # product = Product.objects.get(pk=pk)
    product = get_product(pk)
    context = {
        'categories': categories,
        'title': title,
        'product': product,
    }
    return render(request, 'mainapp/product.html', context)

@cache_page(3600)
def products(request, pk=None, page=1):
    title = 'GeekShop - Каталог'
    # categories = ProductCategory.objects.filter(is_active=True)
    categories = get_links_menu()
    if pk is not None:
        if pk == 0:
            # products = Product.objects.all().order_by('price')
            products = get_products_orederd_by_price()
            category = {'pk': 0}
        else:
            # category = get_object_or_404(categories, pk=pk)
            # products = Product.objects.filter(category=category).order_by('price')
            category = get_category(pk)
            products = get_products_in_category_orederd_by_price(pk)

            title = 'GeekShop - ' + category.name
        context = {
            'title': title,
            'categories': categories,
            'products': products,
            'category': category,
        }
        paginator = Paginator(products, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)
        context.update({'products': products_paginator})
        return render(request, 'mainapp/products.html', context)

    category = {
        'pk': 0,
    }
    products = Product.objects.all().order_by('price')
    context = {
        'title': title,
        'categories': categories,
        'products': products,
        'category': category,
    }
    paginator = Paginator(products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)
    context.update({'products': products_paginator})
    return render(request, 'mainapp/products.html', context)


def contact(request):
    context = {
        'title': 'GeekShop',
    }
    return render(request, 'mainapp/contact.html', context)

mainapp/templates/mainapp/auth_menu.html
{% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auth:edit' %}">
            {{ user.first_name|default:'USER' }}
        </a>
    </li>
    {% if user.is_superuser or user.is_staff %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'admin_staff:index' %}">
                <i class="fas fa-users-cog"></i>
            </a>
        </li>

    {% endif %}
{% endif %}

<li class="nav-item">
    {% if user.is_authenticated %}
        <li class="nav-item">
            <div class="dropdown">
                <a class="nav-link" class="dropdown-toggle" href="" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li class="nav-item">
                        <a class="nav-link" style="color: #1b1e21" href="{% url 'admin:index' %}">Admin Panel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="color: #1b1e21" href="{% url 'authapp:edit' %}">профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="color: #1b1e21" href="{% url 'ordersapp:orders_list' %}">заказы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="color: #1b1e21" href="{% url 'authapp:logout' %}">Выйти</a>
                    </li>
                </ul>
            </div>
        </li>
    {% else %}
        <a class="nav-link" href="{% url 'auth:login' %}">Войти</a>
    {% endif %}
</li>

mainapp/templates/mainapp/base.html
{% load static %}
{% load custom %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}

</head>

<body>
{% include 'mainapp/nav_menu.html' %}

{% block contents %}
{% endblock %}


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<!-- Basket script -->
<script src="{% static 'js/basket.js' %}"></script>

{% block custom_scripts %}
{% endblock %}

</body>

</html>

mainapp/templates/mainapp/carousel.html
{% load static %}
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                 alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                 alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                 alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

mainapp/templates/mainapp/category.html
{% block category %}
    <div class="col-lg-3">

        <h1 class="my-4">GeekShop</h1>
        <div class="list-group">
            {% for category in categories %}
                {% if category.is_active %}
                    <b><a href="{% url 'products:category' category.pk %}"
                          class="list-group-item bg-light">{{ category.name }}
                    </a>
                    </b>
                {% endif %}
            {% endfor %}
        </div>

    </div>
    <!-- /.col-lg-3 -->
{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <title>{{ title | title }}</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
    <!-- Page Content -->

{% endblock %}

mainapp/templates/mainapp/footer.html
<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; GeekShop {% now 'Y' %}</p>
    </div>
    <!-- /.container -->
</footer>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <title>{{ title | title }}</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
    <!-- Page Content -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

mainapp/templates/mainapp/nav_menu.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог</a>
                </li>
                <li class="nav-item">
                    <!--<a class="nav-link" href="{% url 'products:index' %}"><i class="fas fa-shopping-bag"></i></a>-->
                    <a href="{% url 'basket:view' %}" class="basket nav-link">
                        {% if baskets %}
                            <span style="border: #adff66 1px; border-style: outset">&nbsp;Кол-во: {{ baskets|length }} шт. / Сумма: {{ total_sum }} руб.&nbsp;</span>
                            &nbsp;
                        {% endif %}
                        <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% include 'mainapp/auth_menu.html' %}
            </ul>
        </div>
    </div>
</nav>

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load custom %}

{% block css %}
    <title>{{ title | title }}</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            {% include 'mainapp/category.html' %}
            <div class="col-lg-9">
                {% include 'mainapp/carousel.html' %}
                <div class="row">
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card">
                            <img src="{{ product.image|media_folder_products }}" class="card-img-top" alt="...">
                        </div>
                    </div>
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.description }}</p>
                                <a href="{% url 'basketapp:add' product.pk %}">
                                    <button type="button" class="btn btn-outline-success">
                                        Отправить в корзину
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.col-lg-9 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
    {% include 'mainapp/footer.html' %}
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load custom %}

{% block css %}
    <title>{{ title | title }}</title>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            {% include 'mainapp/category.html' %}
            <div class="col-lg-9">
                {% include 'mainapp/carousel.html' %}
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="{% url 'products:product' product.pk %}">
                                    <img class="card-img-top" src="{{ product.image|media_folder_products }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{% url 'products:product' product.pk %}">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }} руб.</h5>
                                    <p class="card-text">{{ product.short_desc }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'basketapp:add' product.pk %}">
                                        <button type="button" class="btn btn-outline-success">
                                            Отправить в корзину
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top" src="/media/products_images/404.jpg"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">Товара в данной категории нет!</h4>
                                    <p class="card-text">Мы работаем над заполнением данной категории!</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- /.row -->
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_previous %} {% url 'products:page' category.pk products.previous_page_number %} {% else %} # {% endif %}">
                                Previous
                            </a>
                        </li>
                        {% for page in products.paginator.page_range %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% url 'products:page' category.pk page %}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}
                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_next %} {% url 'products:page' category.pk products.next_page_number %} {% else %} # {% endif %}">
                                Next
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
            <!-- /.col-lg-9 -->

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    {% include 'mainapp/footer.html' %}

{% endblock %}